#!/bin/bash

# 配置变量
GITLAB_URL="https://git.sy.com"
PROJECT_ID="172"
ACCESS_TOKEN="GR1348941Mvx35pP_xbFjyzCQduNM"
RUNNER_NAME="custom-runner-1"
PIPELINES_JSON=$(curl -s --header "PRIVATE-TOKEN: $ACCESS_TOKEN" \
	  "$GITLAB_URL/api/v4/projects/$PROJECT_ID/pipelines?per_page=100")
echo "$PIPELINES_JSON"
